version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: teste123
    ports:
      - "5432:5432"
    volumes:
      - C:\Users\Jamilson Pereira\Documents\Ambiente Desenvolvimento\Docker-Compose